/**:
  ros__parameters:
    # Configuration essaim
    robot_prefixes: "crazyflie,crazyflie1,crazyflie2,crazyflie3,crazyflie4,crazyflie5,crazyflie6,crazyflie7"
    max_robots: 8
    use_sim_time: true

    # ZONES D'OR ULTRA-STRICTES
    golden_zones_enabled: true
    creation_threshold: 3
    validation_threshold: 4
    disappear_threshold: 5
    creation_timeout: 30.0
    consensus_timeout: 600.0
    validated_timeout: 1200.0
    min_confidence: 0.8
    validation_confidence: 0.9
    suppression_cooldown: 60.0
    golden_cell_value: 75
    topic_golden_zones: '/map_golden_zones'

    # Autres paramètres
    enable_ultra_robuste: true
    ultra_robust_mode: true
    publish_rate: 2.0
    topic_merged_map: '/map_merged'
    topic_weighted_map: '/map_fusion_weighted'
