# Behavioral Rules for DIAMANTS V3 Universe
# Règles comportementales pour agents et système

agent_behavior:
  exploration:
    max_speed: 2.0 # m/s
    min_altitude: 0.5 # m
    max_altitude: 3.0 # m
    obstacle_avoidance_distance: 1.0 # m

  coordination:
    formation_distance: 2.0 # m
    communication_range: 100.0 # m
    priority_levels:
      - emergency
      - formation
      - exploration
      - maintenance

  safety:
    emergency_landing_altitude: 0.1 # m
    battery_critical_level: 20 # %
    max_tilt_angle: 30 # degrees

system_behavior:
  monitoring:
    health_check_interval: 1.0 # seconds
    log_rotation_size: 100MB
    max_log_age_days: 7

  performance:
    cpu_warning_threshold: 80 # %
    memory_warning_threshold: 90 # %
    disk_warning_threshold: 95 # %

  automation:
    max_concurrent_tasks: 5
    task_timeout: 300 # seconds
    retry_attempts: 3
