general:
  time_acceleration: 500000000000000.0
  distance_scale: 1.0e-08
  dt: 1.0e-06
  gazebo_scale: 500000000000000.0
  velocity_scale: 10.0

physics:
  G: 6.6743e-11
  GM_SUN: 1.32712440018e20
  softening: 1e-9
  integration_method: LEAPFROG
  default_engine: LEAPFROG
  numerical_precision: 50

celestial_bodies:
  sun:
    name: sun
    mass: 1.989e10
    position:
      - 0.0
      - 0.0
      - 0.0
    velocity:
      - 0.0
      - 0.0
      - 0.0
    radius: 2.0
    static: false
  mercury:
    name: mercury
    mass: 10000000.0
    position:
      - 3.0
      - 0.0
      - 0.0
    velocity:
      - 0.0
      - 200000.0
      - 0.0
    radius: 0.1
    static: false
    inclination: 7.0
    eccentricity: 0.206
    longitude_ascending_node: 48.3
  venus:
    name: venus
    mass: 8000000.0
    position:
      - 5.0
      - 0.0
      - 0.0
    velocity:
      - 0.0
      - 150000.0
      - 0.0
    radius: 0.15
    static: false
    inclination: 3.4
    eccentricity: 0.007
    longitude_ascending_node: 76.7
  earth:
    name: earth
    mass: 6000000.0
    position:
      - 7.0
      - 0.0
      - 0.0
    velocity:
      - 0.0
      - 120000.0
      - 0.0
    radius: 0.2
    static: false
    inclination: 0.0
    eccentricity: 0.017
    longitude_ascending_node: 0.0
  mars:
    name: mars
    mass: 4000000.0
    position:
      - 9.0
      - 0.0
      - 0.0
    velocity:
      - 0.0
      - 100000.0
      - 0.0
    radius: 0.15
    static: false
    inclination: 1.9
    eccentricity: 0.094
    longitude_ascending_node: 49.6
  jupiter:
    name: jupiter
    mass: 20000000.0
    position:
      - 12.0
      - 0.0
      - 0.0
    velocity:
      - 0.0
      - 80000.0
      - 0.0
    radius: 0.4
    static: false
    inclination: 1.3
    eccentricity: 0.049
    longitude_ascending_node: 100.5
  saturn:
    name: saturn
    mass: 15000000.0
    position:
      - 15.0
      - 0.0
      - 0.0
    velocity:
      - 0.0
      - 70000.0
      - 0.0
    radius: 0.35
    static: false
    inclination: 2.5
    eccentricity: 0.057
    longitude_ascending_node: 113.7
  uranus:
    name: uranus
    mass: 10000000.0
    position:
      - 18.0
      - 0.0
      - 0.0
    velocity:
      - 0.0
      - 60000.0
      - 0.0
    radius: 0.25
    static: false
    inclination: 0.8
    eccentricity: 0.046
    longitude_ascending_node: 74.0
  neptune:
    name: neptune
    mass: 8000000.0
    position:
      - 21.0
      - 0.0
      - 0.0
    velocity:
      - 0.0
      - 50000.0
      - 0.0
    radius: 0.2
    static: false
    inclination: 1.8
    eccentricity: 0.009
    longitude_ascending_node: 131.8

visualization:
  colors:
    mercury:
      - 255
      - 165
      - 0
    venus:
      - 255
      - 215
      - 0
    earth:
      - 0
      - 100
      - 255
    mars:
      - 255
      - 69
      - 0
    jupiter:
      - 255
      - 140
      - 0
    saturn:
      - 255
      - 215
      - 0
    uranus:
      - 64
      - 224
      - 208
    neptune:
      - 0
      - 0
      - 255
  orbit_segments: 100
  orbit_alpha: 0.5
  marker_scale:
    - 2.0
    - 2.0
    - 2.0

gazebo:
  world_name: solar_system_diamants
  physics_plugin: gz-physics-bullet-featherstone-plugin
  max_step_size: 0.001
  real_time_factor: 1.0
  real_time_update_rate: 1000

ros2:
  domain_id: 42
  force_topic_template: /apply_force_{}
  apply_wrench_service: /apply_link_wrench
  physics_namespace: /physics
  visualization_namespace: /visualization

logging:
  level: INFO
  physics_log: /tmp/gravity_engine.log
  bridge_log: /tmp/gazebo_bridge.log
  visualization_log: /tmp/orbit_visualizer.log
  max_file_size: 10MB
  backup_count: 5

testing:
  test_duration: 60
  min_movement_threshold: 1.0
  max_energy_drift: 0.01
  check_frequency: 10
