# 🌌 DIAMANTS V3 - Configuration Environnements Spatiaux
# =====================================================

space_environments:
  lunar_surface:
    description: "Surface lunaire avec terrains procéduraux réalistes"
    gravity: [0.0, 0.0, -1.62] # m/s² (1/6 de la gravité terrestre)
    atmosphere: false
    world_file: "lunar_surface.sdf"
    default_vehicles: ["lunar_rover", "drone_swarm"]
    terrain_features:
      - craters: true
      - rocks: true
      - regolith: true
      - elevation_variation: 500.0 # mètres
    lighting:
      sun_intensity: 1.0
      earth_light: 0.1
      deep_space: true

  mars_surface:
    description: "Surface martienne avec atmosphère simulée"
    gravity: [0.0, 0.0, -3.71] # m/s² (38% de la gravité terrestre)
    atmosphere: true
    atmospheric_pressure: 0.006 # atm (0.6% de la Terre)
    world_file: "mars_surface.sdf"
    default_vehicles: ["mars_rover", "mars_helicopter"]
    terrain_features:
      - canyons: true
      - dust_storms: true
      - polar_caps: false
      - elevation_variation: 2000.0 # mètres
    weather:
      dust_storm_probability: 0.1
      temperature_range: [-143, 35] # Celsius

  asteroid_field:
    description: "Champ d'astéroïdes avec navigation 3D complexe"
    gravity: [0.0, 0.0, 0.0] # microgravité
    atmosphere: false
    world_file: "asteroid_field.sdf"
    default_vehicles: ["mining_drone", "navigation_probe"]
    environment_features:
      - asteroid_count: 50
      - asteroid_size_range: [1.0, 100.0] # mètres
      - rotation_rates: "random"
      - mineral_distribution: "realistic"
    mining:
      valuable_minerals: ["platinum", "rare_earth", "water_ice"]
      extraction_difficulty: "high"

  solar_system:
    description: "Système solaire complet avec orbites réalistes"
    gravity: "n_body_simulation" # Simulation multi-corps
    atmosphere: false
    world_file: "solar_system.sdf"
    default_vehicles: ["satellite_constellation", "deep_space_probe"]
    orbital_bodies:
      - sun: { mass: 1.989e30, radius: 696340000 } # kg, mètres
      - mercury: { mass: 3.301e23, radius: 2439700, orbit_radius: 57.9e9 }
      - venus: { mass: 4.867e24, radius: 6051800, orbit_radius: 108.2e9 }
      - earth: { mass: 5.972e24, radius: 6371000, orbit_radius: 149.6e9 }
      - mars: { mass: 6.417e23, radius: 3389500, orbit_radius: 227.9e9 }
    physics:
      time_scale: 3600.0 # 1 seconde = 1 heure réelle
      orbital_precision: "high"

  space_station:
    description: "Station spatiale modulaire en orbite terrestre"
    gravity: [0.0, 0.0, 0.0] # microgravité
    atmosphere: false
    world_file: "space_station.sdf"
    default_vehicles: ["service_drone", "cargo_vehicle"]
    orbital_parameters:
      altitude: 408000 # mètres (ISS-like)
      inclination: 51.6 # degrés
      period: 5580 # secondes
    station_modules:
      - laboratory: true
      - habitation: true
      - solar_arrays: true
      - docking_ports: 4

  earth_orbit:
    description: "Orbite terrestre avec effets magnétosphériques"
    gravity: "earth_gravity_model"
    atmosphere: "upper_atmosphere"
    world_file: "earth_orbit.sdf"
    default_vehicles: ["satellite_constellation", "orbital_platform"]
    orbital_zones:
      - leo: { min_alt: 160000, max_alt: 2000000 } # Low Earth Orbit
      - meo: { min_alt: 2000000, max_alt: 35786000 } # Medium Earth Orbit
      - geo: { altitude: 35786000 } # Geostationary Orbit
    space_weather:
      solar_wind: true
      magnetic_field: true
      radiation_belts: true

mission_types:
  exploration:
    description: "Mission d'exploration scientifique"
    objectives:
      - terrain_mapping: true
      - sample_collection: true
      - hazard_identification: true
    success_criteria:
      - area_coverage: 80 # pourcentage
      - samples_collected: 10
      - navigation_accuracy: 1.0 # mètres

  mining:
    description: "Mission d'extraction de ressources"
    objectives:
      - resource_identification: true
      - extraction_operations: true
      - transport_logistics: true
    success_criteria:
      - resources_extracted: 1000 # kg
      - extraction_efficiency: 75 # pourcentage
      - equipment_durability: 90 # pourcentage

  construction:
    description: "Mission de construction d'infrastructure"
    objectives:
      - site_preparation: true
      - assembly_operations: true
      - system_integration: true
    success_criteria:
      - construction_progress: 100 # pourcentage
      - structural_integrity: 95 # pourcentage
      - timeline_adherence: 90 # pourcentage

  scientific:
    description: "Mission de recherche scientifique avancée"
    objectives:
      - data_collection: true
      - experiment_execution: true
      - hypothesis_testing: true
    success_criteria:
      - data_quality: 95 # pourcentage
      - experiments_completed: 100 # pourcentage
      - scientific_discoveries: 3 # nombre

  rescue:
    description: "Mission de sauvetage d'urgence"
    objectives:
      - target_location: true
      - obstacle_navigation: true
      - emergency_response: true
    success_criteria:
      - response_time: 600 # secondes
      - navigation_accuracy: 0.5 # mètres
      - mission_success_rate: 100 # pourcentage

  formation_flight:
    description: "Vol en formation coordonnée"
    objectives:
      - formation_maintenance: true
      - coordinated_maneuvers: true
      - communication_relay: true
    success_criteria:
      - formation_precision: 0.1 # mètres
      - communication_reliability: 99 # pourcentage
      - fuel_efficiency: 85 # pourcentage

vehicle_configurations:
  multi_drone_swarm:
    count: 8
    type: "crazyflie_space"
    configuration:
      mass: 0.027 # kg (optimisé pour l'espace)
      thrust_max: 0.6 # N
      battery_capacity: 240 # mAh
      communication_range: 1000 # mètres
      sensors:
        - lidar_3d: true
        - thermal_camera: true
        - magnetometer: true
        - star_tracker: true
    formation_types:
      - tetrahedral: true
      - planar_grid: true
      - adaptive_3d: true

  satellite_constellation:
    count: 12
    type: "cubesat_6u"
    configuration:
      mass: 12.0 # kg
      power_generation: 50 # Watts
      communication_bands: ["S", "X", "Ku"]
      payload_capacity: 5.0 # kg
    orbital_configuration:
      planes: 3
      satellites_per_plane: 4
      phase_offset: 120 # degrés

  space_rover:
    count: 1
    type: "planetary_rover"
    configuration:
      mass: 899.0 # kg (Curiosity-like)
      wheel_count: 6
      max_speed: 4.2 # cm/s
      power_source: "rtg" # Radioisotope Thermoelectric Generator
      scientific_instruments: 10

sensor_suites:
  space_grade_advanced:
    thermal_sensors:
      resolution: "1024x768"
      spectral_bands: ["thermal_ir", "near_ir", "visible"]
      temperature_range: [-273.15, 150.0]
      accuracy: 0.1 # Kelvin

    communication_sensors:
      frequency_bands: ["S", "X", "Ku", "Ka"]
      antenna_gain: 35.0 # dBi
      transmission_power: 100.0 # Watts
      data_rate: 1e6 # bps

    navigation_sensors:
      gps_replacement: "star_tracker"
      imu_grade: "space_qualified"
      magnetometer: "vector_3axis"
      sun_sensors: 6

    scientific_sensors:
      spectrometers: ["visible", "infrared", "xray"]
      particle_detectors: ["cosmic_ray", "solar_wind"]
      gravimeters: "quantum_grade"
      seismometers: "planetary_grade"

physics_validation:
  orbital_mechanics:
    tolerance_position: 0.001 # km
    tolerance_velocity: 0.0001 # km/s
    tolerance_attitude: 0.1 # degrés
    validation_frequency: 20.0 # Hz

  atmospheric_effects:
    drag_coefficient_accuracy: 0.05
    lift_coefficient_accuracy: 0.05
    atmospheric_density_model: "exponential"

  thermal_effects:
    solar_heating: true
    radiative_cooling: true
    thermal_conduction: true
    albedo_effects: true

  gravitational_effects:
    n_body_simulation: true
    tidal_effects: true
    relativistic_corrections: false # Pour missions proche Terre
    gravitational_perturbations: true

performance_targets:
  simulation:
    real_time_factor: 1.0
    physics_step_size: 0.0005 # secondes
    rendering_fps: 60
    memory_usage_max: "8GB"

  mission:
    communication_latency_max: 0.1 # secondes
    navigation_accuracy: 0.1 # mètres
    power_efficiency: 85 # pourcentage
    mission_success_rate: 95 # pourcentage
