# Success Criteria for DIAMANTS V3 Universe
# Critères de succès pour validation missions

mission_success:
  exploration_mission:
    min_area_coverage: 80 # % of target area
    map_quality_threshold: 0.8 # quality score
    completion_time_max: 1800 # seconds (30 min)
    agents_operational: 6 # minimum of 8 agents

  coordination_mission:
    formation_precision: 0.9 # accuracy score
    communication_reliability: 0.95 # success rate
    collision_incidents: 0 # zero tolerance
    synchronization_error: 0.1 # seconds max

  navigation_mission:
    waypoint_accuracy: 0.2 # meters
    path_following_error: 0.3 # meters RMS
    obstacle_avoidance_success: 1.0 # 100%
    landing_precision: 0.5 # meters

system_success:
  stability:
    continuous_operation: 3600 # seconds minimum
    crash_tolerance: 0 # zero crashes
    recovery_capability: 1.0 # 100% recovery

  performance:
    real_time_compliance: 0.95 # 95% on-time
    resource_utilization: 0.7 # optimal usage
    scalability_factor: 1.0 # linear scaling

  integration:
    ros2_compatibility: 1.0 # full compatibility
    gazebo_stability: 0.99 # 99% stable
    framework_cohesion: 1.0 # no conflicts

validation_criteria:
  automated_tests:
    unit_test_coverage: 80 # % minimum
    integration_test_pass: 95 # % minimum
    system_test_success: 90 # % minimum

  manual_validation:
    user_acceptance: 0.9 # score
    documentation_completeness: 0.8 # score
    training_effectiveness: 0.85 # score
